name: coda_wallet
description: Staking-Power wallet worked for Mina on both android and ios, developed by flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.0+33

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql: ^5.1.3
  flutter_bloc: ^7.3.3
  equatable: ^2.0.2
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  flutter_screenutil: ^5.6.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.5
  keyboard_actions: ^4.1.0
  image_gallery_saver: ^1.6.9
  permission_handler: ^7.2.0
  percent_indicator: ^3.0.1
  event_bus: ^2.0.0
#  top_k: '^1.0.1'
  common_utils: ^2.0.2
  intl: ^0.18.0
  url_launcher: ^6.1.10
  package_info: ^2.0.0
  dio: ^5.0.1
  cached_network_image: ^3.2.3
  collection: ^1.15.0
#  social_share: ^2.1.1
  fluttertoast: ^8.1.3
  image_picker: ^0.8.6+1
  password_strength: ^0.2.0
  flutter_secure_storage: ^7.0.1
  flutter_jailbreak_detection: ^1.10.0
  flutter_windowmanager: ^0.2.0
  flutter_secure_screen: ^0.0.1
  loading_animation_widget: ^1.2.0+4
  ffi_mina_signer:
    path: ../ffi_mina_signer/
  appinio_social_share:
    path: ../appinio_social_share
  lecle_flutter_absolute_path: ^0.0.2+1
  screenshot: ^1.3.0
  decimal: ^2.3.2
  flutter_countdown_timer: ^4.1.0
  expandable_page_view: ^1.0.17
  dropdown_button2: ^2.0.0
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 # gql_code_gen: ^0.1.5
  mockito: ^5.0.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - images/copy_gray.png
    - images/copy_white.png
    - images/wallet_tab_unselected.png
    - images/wallet_tab_selected.png
    - images/txns_tab_selected.png
    - images/txns_tab_unselected.png
    - images/stake_tab_unselected.png
    - images/stake_tab_selected.png
    - images/settings_tab_selected.png
    - images/settings_tab_unselected.png
    - images/mina_logo_inner.png
    - images/qr_code_icon.png
    - images/wallet_staked_bg.png
    - images/to_stake_flower.png
    - images/no_staking_bg.png
    - images/back.png
    - images/common_bg.png
    - images/mina_logo_black_inner.png
    - images/mina_logo_black_inner_small.png
    - images/share_mina_logo.png
    - images/account_header.png
    - images/pool_header.png
    - images/qr_scanner.png
    - images/close.png
    - images/sent_success.png
    - images/fee_selected.png
    - images/txn_send.png
    - images/txn_receive.png
    - images/txn_stake.png
    - images/txn_pending.png
    - images/filter_logo.png
    - images/down_expand.png
    - images/arrow_right.png
    - images/create_account.png
    - images/input_delete.png
    - images/password_lock_logo.png
    - images/password_hide.png
    - images/password_show.png
    - images/password_unlock_logo.png
    - images/import_wallet_bg.png
    - images/mina_logo_white_trans.png
    - images/security_alert_blue.png
    - images/security_alert_gray.png
    - images/pwd_show.png
    - images/pwd_hide.png
    - images/new_wallet_alert.png
    - images/send_error_alert.png
    - images/txns_no_data.png
    - images/security_alert_gold.png
    - images/stake_logo_deep_color.png
    - images/account_staked.png
    - images/twitter.png
    - images/discord.png
    - images/mail.png
    - images/telegram.png
    - images/discord_share.png
    - images/facebook_share.png
    - images/facebook_share_disable.png
    - images/instagram_share.png
    - images/instagram_share_disable.png
    - images/sms_share.png
    - images/twitter_share.png
    - images/twitter_share_disable.png
    - images/whatsapp_share.png
    - images/whatsapp_share_disable.png
    - images/telegram_share.png
    - images/telegram_share_disable.png
    - images/verified.png
    - images/icon_search.png
    - images/icon_search_white.png
    - images/txn_wrong.png
    - images/txn_send_blue.png
    - images/txn_receive_green.png
    - images/txn_delegation.png
    - images/txn_list_empty.png
    - images/txn_filter.png
    - images/filter_logo_blue.png
    - images/txn_success.png
    - images/left_arrow_triangle.png
    - images/right_arrow_triangle.png
    - images/not_staked.png
    - images/account_not_active.png
    - images/arrow_down_filling.png
    - images/account_header1.png
    - images/account_list.png
    - images/selected.png
    - images/account_need_sync.png
    - images/account_synced.png
    - images/link.png
    - images/verified_long.png

